"""Protocols for the NoSQL/search/wide-column/time-series surface (FR.NS.1-4, NF.NS.3).

These mirror the SQL :class:`cloud_dog_db.crud.repository.Repository` method names and
return types (``create``/``get``/``update``/``delete``/``list``) and reuse the shared
error model and query specs so callers get one consistent contract across SQL and NoSQL.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from cloud_dog_db.crud.specs import PageResult, QuerySpec

#: A NoSQL document / row is a plain JSON-compatible mapping.
Document = dict[str, Any]


@runtime_checkable
class DocumentRepository(Protocol):
    """FR.NS.1 — generic document repository (MongoDB, CouchDB)."""

    def create(self, document: Document) -> Document: ...
    def get(self, record_id: Any) -> Document: ...
    def update(self, record_id: Any, payload: Document) -> Document: ...
    def delete(self, record_id: Any) -> None: ...
    def list(self, spec: QuerySpec | None = None) -> PageResult[Document]: ...
    def count(self, spec: QuerySpec | None = None) -> int: ...
    def close(self) -> None: ...


@runtime_checkable
class SearchRepository(Protocol):
    """FR.NS.2 — search repository (Elasticsearch, OpenSearch)."""

    def index(self, record_id: Any, document: Document) -> Document: ...
    def get(self, record_id: Any) -> Document: ...
    def delete(self, record_id: Any) -> None: ...
    def list(self, spec: QuerySpec | None = None) -> PageResult[Document]: ...
    def search(self, query: dict[str, Any] | str, spec: QuerySpec | None = None) -> PageResult[Document]: ...
    def refresh(self) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class WideColumnRepository(Protocol):
    """FR.NS.3 — wide-column repository (Cassandra)."""

    def create(self, row: Document) -> Document: ...
    def get(self, key: dict[str, Any]) -> Document: ...
    def update(self, key: dict[str, Any], payload: Document) -> Document: ...
    def delete(self, key: dict[str, Any]) -> None: ...
    def list(self, spec: QuerySpec | None = None) -> PageResult[Document]: ...
    def close(self) -> None: ...


@runtime_checkable
class TimeSeriesRepository(Protocol):
    """FR.NS.4 — time-series repository (Mongo native / OpenSearch data-stream / Postgres partition)."""

    def record(self, point: Document) -> Document: ...
    def record_many(self, points: list[Document]) -> int: ...
    def range(self, start: Any, end: Any, spec: QuerySpec | None = None) -> list[Document]: ...
    def aggregate_by_time_bucket(
        self,
        *,
        value_field: str,
        interval: str,
        start: Any,
        end: Any,
        op: str = "avg",
        spec: QuerySpec | None = None,
    ) -> list[Document]: ...
    def close(self) -> None: ...
